---
abstract: 'Easy DBI access from CGI::Application'
author:
  - 'Mark Stosberg <mark@stosberg.com>'
build_requires:
  DBD::Mock: 0.11
  Test::MockObject: 1.20120301
  Test::More: 1.001002
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Application-Plugin-DBH
requires:
  CGI::Application: 0
  DBI: 0
  parent: 0
resources:
  homepage: https://github.com/frioux/CGI-Application-Plugin-DBH
  repository: https://github.com/frioux/CGI-Application-Plugin-DBH.git
version: 4.04
