--- #YAML:1.0
name: CGI-Application-Plugin-DBH
version: 3.00
author:
  - Mark Stosberg <mark@summersault.com>
abstract: Plugin that adds DBH support to CGI::Application
license: perl
requires:
  CGI::Application: 0
  DBD::Mock: 0.11
  DBI: 0
provides:
  CGI::Application::Plugin::DBH:
    file: lib/CGI/Application/Plugin/DBH.pm
    version: 3.00
generated_by: Module::Build version 0.2606
